en/mkdocs.yml

Change the base path

---

en/docs/quick-start-guides/schedule-your-first-automation.md

Fix broken bi icon

---

en/docs/devant-samples/explore-the-demo-organization.md
en/docs/devant-samples/quick-deploy-a-sample.md
en/docs/devant-samples/samples-overview.md
en/mkdocs.yml

Add quick deploy samples doc

---

en/docs/quick-start-guides/deploy-your-first-event-handler.md
en/mkdocs.yml

Add initial event handler page

---

en/docs/quick-start-guides/schedule-your-first-automation.md

Fix reviewed suggestions in quickstart page

---

en/docs/quick-start-guides/deploy-your-first-ai-agent.md
en/docs/quick-start-guides/deploy-your-first-integration-as-api.md

Refactor quick start guides

---

en/docs/quick-start-guides/deploy-your-first-event-handler.md

Add event handler docs

---

en/docs/quick-start-guides/deploy-your-first-ai-agent.md

Refactor AI Agent Quickstart Guide

---

en/docs/quick-start-guides/deploy-your-first-ai-agent.md

Update the Configurations table

---

en/docs/quick-start-guides/deploy-your-first-ai-agent.md

Refactor the AI Agent Quickstart guide

---

en/docs/devant-concepts/organization.md

$title
https://github.com/wso2-enterprise/devant/issues/927

Fix steps to find org ID

---

README.md
en/docs/devant-concepts/endpoint.md
en/docs/index.md

Remove a broken link and add BI and MI links to the front page

Remove a broken link and add BI, MI links to front page

---

en/docs/index.md
en/docs/quick-start-guides/deploy-your-first-ai-agent.md
en/docs/quick-start-guides/deploy-your-first-integration-as-api.md
en/docs/quick-start-guides/schedule-your-first-automation.md

Rename `VSCode` to `VS Code`

---

en/docs/references/devant-platform-services-billing-and-upgrades.md
en/mkdocs.yml

> $Subject
Fixes: https://github.com/wso2/docs-devant/issues/62

Add Devant Platform Service Billing and Upgrades document

---

en/docs/quick-start-guides/deploy-your-first-file-integration.md

> $subject
Fixes: https://github.com/wso2-enterprise/devant/issues/1118
> Link to the PR for changes to the training content in …

Add quick deploy guide for file integration

---

en/mkdocs.yml

> $subject
> Link to the PR for changes to the training content in https://github.com/wso2/WSO2-Training, if applicable
> Type …

Add file integration guide to mkdocs

---

en/docs/devant-concepts/project.md

> $subject
> Link to the PR for changes to the training content in https://github.com/wso2/WSO2-Training, if applicable
> Type …

Resize images

---

en/docs/quick-start-guides/deploy-your-first-file-integration.md

> $subject
> Link to the PR for changes to the training content in https://github.com/wso2/WSO2-Training, if applicable
> Type …

Add gifs to the file integration quick deploy guide

---

en/docs/quick-start-guides/deploy-your-first-ai-agent.md

> $Subject
> Link to the PR for changes to the training content in https://github.com/wso2/WSO2-Training, if applicable
> Type …

Update AI Agent Quick Start Guide

---

en/docs/references/signup-and-upgrade-guide.md

Fix url issue

---

en/docs/ai/rag-application.md

This PR updates the path to the RAG Ingestion GIF to reflect its new location within the rag-application subdirectory.
Resolves: [https://github.com/wso2/docs-devant/issues/83](https://github.com/wso2/docs-devant/issues/83)
Updated the image path from:
`<a href="{{base_path}}/assets/img/ai/rag-ingestion.gif"><img src="{{base_path}}/assets/img/ai/rag-ingestion.gif" alt="RAG Ingestion" width="80%"></a>`
to:
`<a href="{{base_path}}/assets/img/ai/rag-application/rag-ingestion.gif"><img src="{{base_path}}/assets/img/ai/rag-application/rag-ingestion.gif" alt="RAG Ingestion" width="80%"></a>`
The GIF was moved to a more appropriate subdirectory (rag-application) to better organize related assets.
> Describe the solutions that this feature/fix will introduce to resolve the problems described …

Update GIF path for RAG Ingestion image

---

en/docs/references/install-and-setup-wso2-integrator-bi.md

Fix image loading issue

---

en/docs/references/install-and-setup-wso2-integrator-bi.md

Fix image rendering issue

---

en/docs/configure-vpn/configure-tailscale-vpn.md

Refactor the tailscale vpn docs

---

en/docs/configure-vpn/configure-tailscale-vpn.md

Fix the tailscale docs

---

en/docs/configure-vpn/configure-tailscale-vpn.md

Remove unavailable links

---

en/docs/ai/deploy-your-first-ai-agent.md
en/docs/ai/rag-application.md

Update BI Documentation Links Following Restructure

---

en/docs/quick-start-guides/deploy-your-first-ai-agent.md

Direct to correct AI agent doc

---

en/docs/quick-start-guides/deploy-your-first-integration-as-api.md

Revise step title and fix typo in documentation

---

en/docs/administer/configure-an-external-idp/configure-asgardeo-as-an-external-idp.md
en/docs/administer/configure-an-external-idp/configure-azure-ad-as-an-external-idp.md
en/docs/administer/configure-enterprise-login.md
en/mkdocs.yml

Adds enterprise and external IdP configuration guides to the Devant documentation.
Resolves Issue: https://github.com/wso2-enterprise/devant/issues/1626

Add enterprise and external IdP configuration docs

---

en/docs/administer/configure-enterprise-login.md

Update application name in enterprise login guide
